.TH ANIMATOR 1 "2 April 2017" "animator" "Manual page for animator"
.SH NAME
animator \- create graph animation for input data
.SH SYNOPSIS
.B SOURCE_PATH/animator
[-v]
[-t \fItimeformat\fR]
[-y \fInumber\fR/\fImin\fR/\fIauto\fR]
[-Y \fInumber\fR/\fImax\fR/\fIauto\fR]
[-S \fInumber\fR]
[-T \fInumber\fR]
[-e \fIparam=val:param=val...\fR]
[-f \fIfile\fR]
[-n \fIname\fR]
.IR file ...
.SH DESCRIPTION
animator creates an .mp4 animaton of given input data with respect to time.
In resulting animation is firstly continuously displayed curve for moving average calculated from input data,
which is then followed by curve for actual input data. In the end, the spaces between these two curves
are filled in by different colours above and below the average curve.

Input data can be in more than one file, although time ranges of individual files are expected not to cross each other.
Expected format of input data is timestamp in given format and numeric value separated by space.
Each line of input file contains one such a record.

Parameters of program and resulting animation can be modified by options described in following section and also by configuration file,
while direct option have higher priority than directives in configuration file in case of collision. In case of multiple
appearance of an option or directive in configuration file, the last appearance is valid.

Resulting animation anim.mp4 is saved in directory specified by \fI-n\fR option.

Executability of this program depends on presence of programs ffmpeg(1) and gnuplot(1).
.SH OPTIONS
.TP
-e \fIparam=val:param=val...\fR
Sets effects of animation. \fIparam\fR stands for name of effect parameter, possible names are \fIamplify\fR and \fIsmooth\fR.
\fIval\fR stands for number defining intensity of the effect. Directive for configuration file is \fIEffectParams\fR.

\fIamplify\fR parameter is used for modifying difference between curves for average and actual data for better distinction.
Number \fIval\fR has to be greater than zero andin this case indicates percentage by which are the actual data supposed to move from average curve.
Default value is 0.

\fIsmooth\fR parameter is used for slight decreasing of graphic noise in graph without bigger changes in curve parameters.
Number \fIval\fR has to be greater than zero and indicates intensity of smoothing effect.
.TP
-f \fIfile\fR
Include configuration from \fIfile\fR.

Valid format for options in configuration file is:\fIoption-directive\fR \fIvalue\fR 

There can be only one directive on each line of configuration file, and directive and value are separated by space(s) or tab(s).
The configuration file is case insensitive.
.TP
-n \fIname\fR
Sets \fIname\fR of output directory for resulting animation. If directory of given \fIname\fR exists then \fIname_i\fR directory is used, where i=max(i,0)+1.
Default value is \fgrapAnimation\fR. Directive for configuration file is \fName\fR.
.TP
-S \fInumber\fR
Speed option. Sets number of records from input used for singel frame of animation. Default value is \fI1\fR.
Directive for configuration file is \fISpeed\fR. 
.TP
-t \fItimeformat\fR
Time format value. Sets time format of data in input file. Acceptable variables of date format are \fI%[yYmdHMS]\fR.
Default value is \fI[%Y-%m-%d %H:%M:%S]\fR. Directive for configuration file is \fITimeFormat\fR.
.TP
-T \fInumber\fR
Time option. Sets length of resulting animation in seconds. Directive for configuration file is \fITime\fR. 
.TP
-y \fInumber\fR/\fImin\fR/\fIauto\fR
Sets lowest Y-axis value of graph. Possible arguments are specific \fInumber\fR, \fImin\fR keyword or \fIauto\fR keyword.

\fImin\fR sets lowest value from input data. If \fIauto\fR is selected, the range of graph moves with appearing values.

Default value is \fIauto\fR. Directive for configuration file is \fIYmin\fR.
.TP
-Y \fInumber\fR/\fImax\fR/\fIauto\fR
Sets highest Y-axis value of graph. Possible arguments are specific \fInumber\fR, \fImax\fR keyword or \fIauto\fR keyword.

\fImax\fR sets highest value from input data. If \fIauto\fR is selected, the range of graph moves with appearing values.

Default value is \fIauto\fR. Directive for configuration file is \fIYmax\fR.
.TP
-v
Turns on verbose mode. Directiove for configuration file is \fIVerbose\fR.

.SH EXIT STATUS
There are two possible values we can get on exit of program.

\fI0\fR - animation was succesfully created without fatal error

\fI1\fR - program ended on fatal error without creating animation.
.SH FILES
For runnig this program, two files are necessary.

\fIanimator\fR - script itself.

\fIdates.pl\fR - perl script for strftime processing
\fIdatestd.pl\fR - perl script for strftime processing

.SH AUTHOR
Ondřej Naňka; nankaond@fit.cvut.cz, nankaond@cvut.cz
.SH SEE ALSO
ffmpeg(1), gnuplot(1)
